### ISSUE TITLE
ci(tests): implement automatic testing via GitHub Actions

### ISSUE THREAD

**Issue by berntpopp** [hassansaei/VNtyper#68]
We currently lack a continuous integration setup that runs our test suite automatically on each commit or pull request. This makes it harder to ensure that new code changes do not introduce regressions. Implementing GitHub Actions for automated testing will help maintain code quality and streamline the review process.

**Goals**  
1. Configure a GitHub Actions workflow to run all relevant tests (unit, integration, etc.) on each push and pull request.  
2. Generate a clear pass/fail status for contributors and maintainers.

**Acceptance Criteria**  
- Creation of a `.github/workflows/tests.yml` (or similarly named) file that sets up the CI environment.  
- Inclusion of steps to install dependencies (e.g., using `requirements.txt` or `conda` environment).  
- Execution of the project’s test suite (unit tests, coverage, etc.).  
- Documentation in `README.md` or `CONTRIBUTING.md` explaining how to run tests locally and what to expect in CI.

**Additional Context**  
- We can potentially integrate coverage reporting (e.g., Codecov) later.  
- The workflow should be flexible enough to be extended for lint checks or building Docker images in future.

**Comment by berntpopp** [comment]
### Proposed GitHub Actions Workflow

1. **Workflow file**: Create a file named `.github/workflows/tests.yml` with the following content:

```yaml
name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Or use conda/mamba if you prefer:
          # conda env create -f environment.yml
          # conda activate <env_name>

      - name: Run tests
        run: |
          pytest tests --maxfail=1 --disable-warnings -v
```

2. **Dependencies**:  
   - Ensure you have a `requirements.txt` (or `environment.yml` for conda) listing all needed Python libraries for your tests (e.g., `pytest`, `requests`, etc.).  
   - This script sets up the environment and installs those dependencies before running `pytest`.  

3. **Test Execution**:  
   - Our existing tests are located in `tests/unit` and `tests/integration`.  
   - The `test_data_config.json` approach automatically downloads any missing data from `server_base_url`, verifying MD5 sums to ensure integrity.  
   - You can see the pass/fail status in GitHub under “Actions” and on each pull request.  

4. **Documentation**:  
   - In your `README.md` or `CONTRIBUTING.md`, add a short section explaining:  
     - **Local Testing**:  
       ```bash
       pip install -r requirements.txt
       pytest tests
       ```  
       or with conda:
       ```bash
       conda env create -f environment.yml
       conda activate <env_name>
       pytest tests
       ```  
     - **CI**: The GitHub Actions workflow automatically runs these same tests on each push and pull request, providing a pass/fail status.  

With these steps, our CI environment will automatically test new code changes, providing more confidence that we don’t introduce regressions. Feel free to extend the workflow later for coverage reports, lint checks, or Docker builds.
